### PR TITLE
Feature/hdf 65 submodules

### PR DESCRIPTION
**Pull request by barryhalo**
Master and develop branches are still empty, so use `feature/hdf-65-submodules` if you want to try it in your local

Tests in CI/CD needs to be adjusted @schystz let's discuss tomorrow

### CODE REVIEW

**Review by bitcoinbrisbane — CHANGES_REQUESTED** [review]
Few suggestions

**Review by tracyarciaga — CHANGES_REQUESTED** [review]
@barryhalo I tried to fetch all submodules as specified in the readme but i got this error

```
TracynoMacBook-Pro:halodao-exchange tracylee$ git submodule update --remote
Cloning into '/Users/tracylee/Documents/dev/HaloDao/halodao-exchange/halodao-interface'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HaloDAO/halodao-interface.git' into submodule path '/Users/tracylee/Documents/dev/HaloDao/halodao-exchange/halodao-interface' failed
Failed to clone 'halodao-interface'. Retry scheduled
Cloning into '/Users/tracylee/Documents/dev/HaloDao/halodao-exchange/halodao-rewards'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:HaloDAO/halo-rewards.git' into submodule path '/Users/tracylee/Documents/dev/HaloDao/halodao-exchange/halodao-rewards' failed
Failed to clone 'halodao-rewards'. Retry scheduled
Cloning into '/Users/tracylee/Documents/dev/HaloDao/halodao-exchange/halodao-interface'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Review by schystz — COMMENTED** [review]
Hi @barryhalo , I think we don't need to add the `.github` folder anymore in the root dir (that is previously for monorepo approach). Aside from that left a few minor comments as well.

**Review by schystz — APPROVED** [review]
Last round of changes looks good to me, so approving!

**Pull request merged**
